### ISSUE TITLE
Update installation instructions to include r-universe option

### ISSUE THREAD

**Issue by AngusMcLure** [AngusMcLure/PoolTestR#16]
Discovered r-universe and found that [PoolTestR](https://angusmclure.r-universe.dev/PoolTestR) is already on it. The website automatically makes binaries from github that are installable as if from CRAN. This will simplify installation of the latest dev version for people who don't have all the RTools set up (and will speed up installation for everyone)

**Comment by caitlinch** [comment]
Updated installation instructions to outline the three ways to download/install PoolTestR and added instructions for installing development versions from R-universe – see https://github.com/AngusMcLure/PoolTestR/commit/8d549e3550c80b9fb1c1b60dd82a195fcb1bded2
