### ISSUE TITLE
Include `robust` options (i.e. posterior median estimates) for all prevalence estimate functions

### ISSUE THREAD

**Issue by AngusMcLure** [AngusMcLure/PoolTestR#17]
Functions:

- [x] getPrevalence.brmsfit
- [x] PoolPrev (bayesian estimates)
- [x] HierPoolPrev

**Comment by caitlinch** [comment]
Completed and merged into main - see commit https://github.com/AngusMcLure/PoolTestR/commit/a5a814fd47b05742712375c68059649ae492c0f2
