### ISSUE TITLE
Include `all.negative.pools` option for appropriate handling of all negative pools

### ISSUE THREAD

**Issue by AngusMcLure** [AngusMcLure/PoolTestR#18]
When all pools are negative the most natural point estimate of prevalence is 0, and the natural interval to calculate is the one-sided interval. This is what is calculated always for the MLE estimates in `PoolPrev`. Since the MLE is 0 in this case, this is only natural. However, to implement this for any of the Bayesian analyses requires a special option. Bayesian functions to implement this for:

- [x] PoolPrev (Bayesian estimates)
- [x] HierPoolPrev
- [x] getPrevalence.brmsfit

**Comment by caitlinch** [comment]
Completed and merged into main
https://github.com/AngusMcLure/PoolTestR/commit/a5a814fd47b05742712375c68059649ae492c0f2
